version: "3.9"
services:
  url-shortener:
    image: service-url-shortener
    container_name: url-shortener
    environment:
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=url_shortener
      - JWT_SECRET=secret
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - database
    restart: always

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=url_shortener
    ports:
      - 127.0.0.1:5432:5432
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    restart: always
